# Generated by Django 5.0.7 on 2024-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='static'),
        ),
    ]
