# Generated by Django 5.0.7 on 2024-07-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
