# Generated by Django 5.0.7 on 2024-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
